on:
    push:
    pull_request_target:
        types: [opened, synchronize, reopened]

jobs:
    pylint:
        strategy:
            matrix:
                python-version: ['3.8', '3.9', '3.10', '3.11']

        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v4

          - name: Set up Python ${{ inputs.python-version }}
            uses: actions/setup-python@v5
            with:
              python-version: ${{ inputs.python-version }}

          - name: Install pylint
            run:  | 
              python -m pip install --upgrade pip
              python -m pip install -e '.[tests]'

          - name: Code check
            run:  pylint --rcfile=.pylintrc --exit-zero --output-format=parseable:pylint.log,text tests ifsbench scripts

    pytest:
        strategy:
            matrix:
                python-version: ['3.8', '3.9', '3.10', '3.11']
        uses: ecmwf-actions/reusable-workflows/.github/workflows/qa-pytest-pyproject.yml@v2
        with:
            python-version: ${{ matrix.python-version }}
