name: pytest

on:
  # Triggers the workflow on push events
  push:
    branches: [ 'main' ]
    tags-ignore: [ '**' ]

  # Triggers the workflow on pull request events
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    pylint:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v4

          - name: Set up Python 3.11
            uses: actions/setup-python@v5
            with:
              python-version: '3.11'

          - name: Install pylint
            run:  | 
              python -m pip install --upgrade pip
              python -m pip install -e '.[tests]'

          - name: Code check
            run:  pylint --rcfile=.pylintrc --output-format=parseable:pylint.log,text tests ifsbench scripts

    pytest:
        strategy:
            matrix:
                python-version: ['3.8', '3.9', '3.10', '3.11']
        uses: ecmwf-actions/reusable-workflows/.github/workflows/qa-pytest-pyproject.yml@v2
        with:
            python-version: ${{ matrix.python-version }}
